version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: ai_tutor_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db

  # Redis
  redis:
    image: redis:7-alpine
    container_name: ai_tutor_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Django Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai_tutor_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - MONGODB_HOST=mongodb
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"

  # Celery Worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai_tutor_celery
    restart: always
    environment:
      - MONGODB_HOST=mongodb
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    command: celery -A backend worker -l info

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_tutor_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data: