# Generated by Django 4.2.25 on 2025-10-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("ai_tutor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyrecommendation",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="studyrecommendation",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.lesson",
            ),
        ),
    ]
