# Generated by Django 4.2.25 on 2025-10-22 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("learning_style", "Learning Style Clustering"),
                            ("performance_prediction", "Performance Prediction"),
                            ("sentiment_analysis", "Sentiment Analysis"),
                            ("recommendation", "Recommendation System"),
                        ],
                        max_length=30,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("algorithm", models.CharField(max_length=100)),
                ("hyperparameters", models.JSONField(default=dict)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                ("model_file_path", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=False)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_models",
                "ordering": ["-trained_at"],
            },
        ),
    ]
