# Generated by Django 4.2.25 on 2025-10-22 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_enrollments", models.IntegerField(default=0)),
                ("active_students", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("average_progress", models.FloatField(default=0.0)),
                (
                    "average_time_to_complete",
                    models.FloatField(default=0.0, help_text="In days"),
                ),
                ("average_quiz_score", models.FloatField(default=0.0)),
                ("pass_rate", models.FloatField(default=0.0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("total_reviews", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_analytics",
            },
        ),
        migrations.CreateModel(
            name="LearningAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_study_time",
                    models.IntegerField(
                        default=0, help_text="Total study time in minutes"
                    ),
                ),
                ("average_daily_time", models.FloatField(default=0.0)),
                (
                    "current_streak",
                    models.IntegerField(default=0, help_text="Current daily streak"),
                ),
                ("longest_streak", models.IntegerField(default=0)),
                ("courses_enrolled", models.IntegerField(default=0)),
                ("courses_completed", models.IntegerField(default=0)),
                ("lessons_completed", models.IntegerField(default=0)),
                ("quizzes_taken", models.IntegerField(default=0)),
                ("quizzes_passed", models.IntegerField(default=0)),
                ("average_quiz_score", models.FloatField(default=0.0)),
                ("chat_messages_sent", models.IntegerField(default=0)),
                ("ai_content_generated", models.IntegerField(default=0)),
                ("predicted_success_rate", models.FloatField(blank=True, null=True)),
                ("at_risk", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "learning_analytics",
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("course_view", "Course View"),
                            ("lesson_view", "Lesson View"),
                            ("quiz_attempt", "Quiz Attempt"),
                            ("chat_message", "Chat Message"),
                            ("content_generation", "Content Generation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
